// dashboard
export const DASHBOARD_TYPE = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: '/icons/dashboard-home.svg',
    children: [
      {
        id: 'general',
        label: 'General',
        shortLabel: 'General',
        path: '/dashboard/general',
        icon: '/images/dashboard-home.svg',
        iconActive: '/images/dashboard-home-active.svg',
        children: [
          {
            id: 'fastFeatures',
            label: 'Fast Features',
            path: '/dashboard/general/fast-features',
            children: [],
          },
          {
            id: 'qrCommunity',
            label: 'QR Community',
            path: '/dashboard/general/qr-community',
            children: [
              {
                id: 'qrNewFeeds',
                label: 'QR News Feed',
                path: '/dashboard/general/qr-community/qr-news-feed',
                children: [],
              },
              {
                id: 'news',
                label: 'News',
                path: '/dashboard/general/qr-community/news',
                children: [],
              },
              {
                id: 'crossSellingItems',
                label: 'Cross-Selling Items',
                path: '/dashboard/general/qr-community/cross-selling-items',
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: 'transaction',
        label: 'Transaction Management',
        shortLabel: 'Transaction',
        path: '/dashboard/transaction',
        icon: '/images/clipboard-list.svg',
        iconActive: '/images/clipboard-list-active.svg',
        children: [],
      },
      {
        id: 'bankAccount',
        label: 'Bank Account',
        shortLabel: 'Account',
        path: '/dashboard/bank-account',
        icon: '/images/money-bank.svg',
        iconActive: '/images/money-bank-active.svg',
        children: [],
      },
      {
        id: 'extensions',
        label: 'Extensions',
        path: '/dashboard/extensions',
        icon: '/images/codes-tags-code-qr.svg',
        iconActive: '/images/codes-tags-code-qr-active.svg',
        children: [],
      },
      {
        id: 'setting',
        label: 'Setting',
        path: '/dashboard/setting',
        icon: '/images/settings-machine.svg',
        iconActive: '/images/settings-machine-active.svg',
        children: [],
      },
    ],
  },
  {
    id: 'agent-dashboard',
    label: 'Agent Dashboard',
    path: '/agent-dashboard',
    children: [
      {
        id: 'businessInformation',
        label: 'Business Information',
        shortLabel: 'Business',
        path: '/agent-dashboard/business-information',
        icon: '/images/contact-notebook-note.svg',
        iconActive: '/images/contact-notebook-note-active.svg',
        children: [
          {
            id: 'agentInformation',
            label: 'Agent Information',
            path: '/agent-dashboard/business-information/agent-information',
            children: [],
          },
          {
            id: 'servicesConnect',
            label: 'Services Connect',
            path: '/agent-dashboard/business-information/services-connect',
            children: [],
          },
          {
            id: 'promotionPrograms',
            label: 'Promotion Programs',
            path: '/agent-dashboard/business-information/promotion-programs',
            children: [],
          },
        ],
      },
      {
        id: 'sales',
        label: 'Sales Management',
        shortLabel: 'Sales',
        path: '/agent-dashboard/sales',
        icon: '/images/shopping-basket.svg',
        iconActive: '/images/shopping-basket-active.svg',
        children: [
          {
            id: 'managementSales',
            label: 'Sales Management',
            path: '/agent-dashboard/sales/sales-management',
            children: [],
          },
          {
            id: 'managementRefunds',
            label: 'Refund Management',
            path: '/agent-dashboard/sales/refund-management',
            children: [],
          },
          {
            id: 'createOrder',
            label: 'Create Order',
            path: '/agent-dashboard/sales/create-order',
            children: [],
          },
        ],
      },
      {
        id: 'statisticalReport',
        label: 'Statistical Report',
        shortLabel: 'Statistical',
        path: '/agent-dashboard/statistical-report',
        icon: '/images/money-graph-pie-chart.svg',
        iconActive: '/images/money-graph-pie-chart-active.svg',
        children: [
          {
            id: 'salesStatistics',
            label: 'Sales Statistics',
            path: '/agent-dashboard/statistical-report/sales-statistics',
            children: [],
          },
          {
            id: 'commodityStatistics',
            label: 'Commodity Statistics',
            path: '/agent-dashboard/statistical-report/commodity-statistics',
            children: [],
          },
          {
            id: 'customerStatistics',
            label: 'Customer Statistics',
            path: '/agent-dashboard/statistical-report/customer-statistics',
            children: [],
          },
        ],
      },
      {
        id: 'storeAndPointOfSale',
        label: 'Store And POS',
        shortLabel: 'Store&Point',
        path: '/agent-dashboard/store-pos',
        icon: '/images/shopping-store-factory-building.svg',
        iconActive: '/images/shopping-store-factory-building-active.svg',
        children: [
          {
            id: 'storeList',
            label: 'Store List',
            path: '/agent-dashboard/store-pos/store-list',
            children: [],
          },
          {
            id: 'addNewStore',
            label: 'Add New Store',
            path: '/agent-dashboard/store-pos/add-new-store',
            children: [],
          },
        ],
      },
      {
        id: 'employees',
        label: 'Employees',
        shortLabel: 'Employees',
        path: '/agent-dashboard/employees',
        icon: '/images/user-multiple.svg',
        iconActive: '/images/user-multiple-active.svg',
        children: [
          {
            id: 'employeeList',
            label: 'Employee List',
            path: '/agent-dashboard/employees/employee-list',
            children: [],
          },
          {
            id: 'addNewEmployee',
            label: 'Add New Employee',
            path: '/agent-dashboard/employees/add-new-employee',
            children: [],
          },
        ],
      },
      {
        id: 'customers',
        label: 'Customers',
        shortLabel: 'Customers',
        path: '/agent-dashboard/customers',
        icon: '/images/user-full-body.svg',
        iconActive: '/images/user-full-body-active.svg',
        children: [
          {
            id: 'customerList',
            label: 'Customer List',
            path: '/agent-dashboard/customers/customer-list',
            children: [],
          },
          {
            id: 'addNewCustomer',
            label: 'Add New Customer',
            path: '/agent-dashboard/customers/add-new-customer',
            children: [],
          },
        ],
      },
      {
        id: 'products',
        label: 'Products',
        shortLabel: 'Products',
        path: '/agent-dashboard/products',
        icon: '/images/shopping-bag-hand-bag.svg',
        iconActive: '/images/shopping-bag-hand-bag-active.svg',
        children: [
          {
            id: 'productList',
            label: 'Product List',
            path: '/agent-dashboard/products/product-list',
            children: [],
          },
          {
            id: 'addNewProduct',
            label: 'Add New Product',
            path: '/agent-dashboard/products/add-new-product',
            children: [],
          },
          {
            id: 'inventoryManagement',
            label: 'Inventory Management',
            path: '/agent-dashboard/products/inventory-management',
            children: [],
          },
        ],
      },
      {
        id: 'support',
        label: 'Support',
        shortLabel: 'Support',
        path: '/agent-dashboard/support',
        icon: '/images/help-customer-support.svg',
        iconActive: '/images/help-customer-support-active.svg',
        children: [],
      },
    ],
  },
];
